[build]
  base = "."
  command = "echo 'Flask app - no build step required'"
  publish = "frontend"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "backend"
  python_runtime = "python3.9"

[dev]
  command = "cd backend && python app.py"
  port = 5000
  publish = "frontend"
