[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
FLASK_ENV = "production"
PYTHONPATH = "/app/backend"
